languages:
  - et
  - en
  - ru
  - de
parameters:
  checkpoint_path: models/domain-detection-model
  tokenizer_path: models/tokenizer
  labels:
    0: general
    1: crisis
    2: legal
    3: military