exchange: domain-detection
# List of supported languages. 2-letter codes should be used (if available)
languages:
  -

# TODO Parameters required by the DomainDetectionWorker, the keys in this file should match the arguments of the class.
parameters:
  some_parameter: some_value