channels:
  - pytorch
  - anaconda
  - conda-forge
dependencies:
  - python=3.9.7
  - pytorch==1.10.0
  - torchvision==0.11.1
  - torchaudio==0.10.0
  - cpuonly==2.0
  - pyyaml==5.3.1
  - pika==1.2.0
  - nltk==3.5
  - transformers=4.9.2
  - pydantic==1.8.2